//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.AppMessage", typeof(AppMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống sẽ tự động huỷ kế hoạch &quot;{0}&quot; của bạn trong khoảng {1} tiếng nữa. Mau vào xác nhận tham gia đi nào..
        /// </summary>
        public static string DESC_NOTIFY_BODY_BEFORE_PLAN_CANCEL_PENDING {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_BEFORE_PLAN_CANCEL_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống sẽ tự động huỷ kế hoạch &quot;{0}&quot; của bạn trong khoảng {1} tiếng nữa. Mau vào chốt kế hoạch đi nào..
        /// </summary>
        public static string DESC_NOTIFY_BODY_BEFORE_PLAN_CANCEL_REGISTERING {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_BEFORE_PLAN_CANCEL_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có đơn hàng mới, mau kiểm tra..
        /// </summary>
        public static string DESC_NOTIFY_BODY_NEW_ORDER {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_NEW_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã huỷ đơn hàng {1}.
        /// </summary>
        public static string DESC_NOTIFY_BODY_ORDER_CANCEL {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_ORDER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng {0} đã được thanh toán..
        /// </summary>
        public static string DESC_NOTIFY_BODY_ORDER_FINISHED {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_ORDER_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã bị chặn khỏi kế hoạch &quot;{0}&quot; bởi trưởng đoàn {1}..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_BLOCK {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch &quot;{0}&quot; đã bị huỷ vì bạn không xác nhận tham gia trong thời hạn cho phép..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_CANCEL_PENDING {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_CANCEL_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch &quot;{0}&quot; đã bị huỷ. Hệ thống đã hoàn lại số Gcoin bạn đã góp vào kế hoạch (nếu có)..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_CANCEL_REGISTERING {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_CANCEL_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thành viên của kế hoạch &quot;{0}&quot; đã được chốt. Hãy xem những người đồng hành cùng bạn là ai nào..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_CONFIRM {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ {0} ngày nữa là tới ngày xuất phát của kế hoạch &quot;{1}&quot; rồi. Mau chuẩn bị hành lý nào..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_DEPART {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_DEPART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đi phượt &quot;{0}&quot; sẽ bắt đầu lúc {1} hôm nay. Chúc bạn có 1 chuyến đi vui vẻ..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_DEPART_TODAY {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_DEPART_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTSS ghi nhận kế hoạch &quot;{0}&quot; đã hoàn tất và hoàn số Gcoin còn lại trong quỹ cho thành viên..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_FINISH {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch &quot;{0}&quot; đã đủ người. Mau vào chốt danh sách thành viên đi bồ tèo..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_FULL {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã mời bạn tham gia kế hoạch &quot;{1}&quot;..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_INVITE {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã bị loại khỏi kế hoạch &quot;{0}&quot; bởi trưởng đoàn {1}..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_REMOVE {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ check-in xác nhận thực hiện kế hoạch để nhận điểm uy tín nhé..
        /// </summary>
        public static string DESC_NOTIFY_BODY_PLAN_VERIFY {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_BODY_PLAN_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch sắp bị huỷ..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_BEFORE_PLAN_CANCEL {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_BEFORE_PLAN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có đơn hàng mới..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_NEW_ORDER {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_NEW_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng bị huỷ.
        /// </summary>
        public static string DESC_NOTIFY_TITLE_ORDER_CANCEL {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_ORDER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đã được thanh toán..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_ORDER_FINISHED {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_ORDER_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị chặn khỏi kế hoạch..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_BLOCK {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch bị huỷ..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_CANCEL {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chốt danh sách thành viên..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_CONFIRM {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất phát đã cận kề..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_DEPART {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_DEPART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tới ngày xuất phát..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_DEPART_TODAY {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_DEPART_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch hoàn tất..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_FINISH {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập trung đông đủ rồi..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_FULL {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lời mời tham gia kế hoạch..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_INVITE {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị loại khỏi kế hoạch..
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_REMOVE {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đến nơi chưa &gt;.&lt;.
        /// </summary>
        public static string DESC_NOTIFY_TITLE_PLAN_VERIFY {
            get {
                return ResourceManager.GetString("DESC_NOTIFY_TITLE_PLAN_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách tạo đơn hàng..
        /// </summary>
        public static string DESC_ORDER_TRACE_CREATED {
            get {
                return ResourceManager.GetString("DESC_ORDER_TRACE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đã hoàn tất, nhà cung cấp đã được thanh toán..
        /// </summary>
        public static string DESC_ORDER_TRACE_FINISHED {
            get {
                return ResourceManager.GetString("DESC_ORDER_TRACE_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} xác nhận đơn hàng..
        /// </summary>
        public static string DESC_ORDER_TRACE_PREPARED {
            get {
                return ResourceManager.GetString("DESC_ORDER_TRACE_PREPARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} xác nhận đã hoàn thành phục vụ đơn hàng..
        /// </summary>
        public static string DESC_ORDER_TRACE_SERVED {
            get {
                return ResourceManager.GetString("DESC_ORDER_TRACE_SERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán đơn hàng {0}..
        /// </summary>
        public static string DESC_TRANSACTION_ORDER_COMPLETE {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_ORDER_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán đơn hàng của kế hoạch &quot;{0}&quot;..
        /// </summary>
        public static string DESC_TRANSACTION_ORDER_CREATE {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_ORDER_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tiền từ đơn hàng..
        /// </summary>
        public static string DESC_TRANSACTION_ORDER_REFUND {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_ORDER_REFUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bù tiền cho kế hoạch &quot;{0}&quot;.
        /// </summary>
        public static string DESC_TRANSACTION_PLAN_CONFIRM {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_PLAN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng quỹ tham gia kế hoạch &quot;{0}&quot;..
        /// </summary>
        public static string DESC_TRANSACTION_PLAN_JOIN {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_PLAN_JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tiền từ kế hoạch..
        /// </summary>
        public static string DESC_TRANSACTION_PLAN_REFUND {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_PLAN_REFUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tiền phụ thu từ kế hoạch &quot;{0}&quot;.
        /// </summary>
        public static string DESC_TRANSACTION_PLAN_SURCHARGE {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_PLAN_SURCHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền vào ví.
        /// </summary>
        public static string DESC_TRANSACTION_TOPUP {
            get {
                return ResourceManager.GetString("DESC_TRANSACTION_TOPUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã đăng nhập ở thiết bị khác..
        /// </summary>
        public static string ERR_ACCOUNT_ALREADY_SIGNED_IN {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_ALREADY_SIGNED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc mật khẩu không chính xác..
        /// </summary>
        public static string ERR_ACCOUNT_AUTHORIZE_FAIL {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_AUTHORIZE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị chặn khỏi hệ thống..
        /// </summary>
        public static string ERR_ACCOUNT_BLOCKED {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mã định danh thiết bị..
        /// </summary>
        public static string ERR_ACCOUNT_DEVICE_TOKEN_EMPTY {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_DEVICE_TOKEN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không phù hợp.
        /// </summary>
        public static string ERR_ACCOUNT_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy địa chỉ email..
        /// </summary>
        public static string ERR_ACCOUNT_EMAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_EMAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email đã được sử dụng..
        /// </summary>
        public static string ERR_ACCOUNT_EMAIL_USED {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_EMAIL_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản chứa ký tự không phù hợp..
        /// </summary>
        public static string ERR_ACCOUNT_NAME_INVALID {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tên người dùng phải trong khoảng {0} - {1} ký tự..
        /// </summary>
        public static string ERR_ACCOUNT_NAME_LENGTH {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin người dùng..
        /// </summary>
        public static string ERR_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống..
        /// </summary>
        public static string ERR_ACCOUNT_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mật khẩu phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_ACCOUNT_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã được sử dụng..
        /// </summary>
        public static string ERR_ACCOUNT_PHONE_USED {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_PHONE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ mới trùng khớp hồ sơ cũ..
        /// </summary>
        public static string ERR_ACCOUNT_UPDATE_EMPTY {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_UPDATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_ADDRESS_LENGTH {
            get {
                return ResourceManager.GetString("ERR_ADDRESS_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền truy cập..
        /// </summary>
        public static string ERR_AUTHORIZE {
            get {
                return ResourceManager.GetString("ERR_AUTHORIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư không đủ để thanh toán..
        /// </summary>
        public static string ERR_BALANCE_NOT_ENOUGH {
            get {
                return ResourceManager.GetString("ERR_BALANCE_NOT_ENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kênh nhận thông báo không hợp lệ..
        /// </summary>
        public static string ERR_CHANNEL_INVALID {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin định danh..
        /// </summary>
        public static string ERR_CLAIM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_CLAIM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình hệ số đảm bảo ngân sách kế hoạch chỉ cho phép trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_CONFIG_BUDGET_ASSURED_PCT {
            get {
                return ResourceManager.GetString("ERR_CONFIG_BUDGET_ASSURED_PCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình điểm tin cậy chỉ cho phép trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_CONFIG_DEFAULT_PRESTIGE_POINT {
            get {
                return ResourceManager.GetString("ERR_CONFIG_DEFAULT_PRESTIGE_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình mức tăng giá dịch vụ lưu trú dịp lễ chỉ cho phép trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_CONFIG_HOLIDAY_LODGING_UP_PCT {
            get {
                return ResourceManager.GetString("ERR_CONFIG_HOLIDAY_LODGING_UP_PCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình mức tăng giá dịch vụ ăn uống dịp lễ chỉ cho phép trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_CONFIG_HOLIDAY_MEAL_UP_PCT {
            get {
                return ResourceManager.GetString("ERR_CONFIG_HOLIDAY_MEAL_UP_PCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình mức tăng giá dịch vụ thuê xe tự lái dịp lễ chỉ cho phép trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_CONFIG_HOLIDAY_RIDING_UP_PCT {
            get {
                return ResourceManager.GetString("ERR_CONFIG_HOLIDAY_RIDING_UP_PCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tham số cấu hình..
        /// </summary>
        public static string ERR_CONFIG_MISSING {
            get {
                return ResourceManager.GetString("ERR_CONFIG_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình khoảng cách ngày đặt dịch vụ tối thiểu chỉ cho phép trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_CONFIG_ORDER_DATE_MIN_DIFF {
            get {
                return ResourceManager.GetString("ERR_CONFIG_ORDER_DATE_MIN_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị nạp tiền không hợp lệ..
        /// </summary>
        public static string ERR_CONFIG_TOPUP_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERR_CONFIG_TOPUP_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cấu hình tiền nạp chỉ cho phép trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_CONFIG_TOPUP_VALUE {
            get {
                return ResourceManager.GetString("ERR_CONFIG_TOPUP_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toạ độ không nằm trong vùng hỗ trợ..
        /// </summary>
        public static string ERR_COORDINATE_INVALID {
            get {
                return ResourceManager.GetString("ERR_COORDINATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thất bại..
        /// </summary>
        public static string ERR_DB_UPDATE {
            get {
                return ResourceManager.GetString("ERR_DB_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hoạt động tương ứng..
        /// </summary>
        public static string ERR_DESTINATION_ACTIVITY_INVALID {
            get {
                return ResourceManager.GetString("ERR_DESTINATION_ACTIVITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_DESTINATION_COMMENT_LENGTH {
            get {
                return ResourceManager.GetString("ERR_DESTINATION_COMMENT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả địa điểm phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_DESTINATION_DESCRIPTION_LENGTH {
            get {
                return ResourceManager.GetString("ERR_DESTINATION_DESCRIPTION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên địa điểm phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_DESTINATION_NAME_LENGTH {
            get {
                return ResourceManager.GetString("ERR_DESTINATION_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin về địa điểm..
        /// </summary>
        public static string ERR_DESTINATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_DESTINATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mùa tương ứng..
        /// </summary>
        public static string ERR_DESTINATION_SEASON_INVALID {
            get {
                return ResourceManager.GetString("ERR_DESTINATION_SEASON_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy địa hình tương ứng..
        /// </summary>
        public static string ERR_DESTINATION_TOPOGRAPHIC_INVALID {
            get {
                return ResourceManager.GetString("ERR_DESTINATION_TOPOGRAPHIC_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức thanh toán không phù hợp..
        /// </summary>
        public static string ERR_ENUM_GATEWAY {
            get {
                return ResourceManager.GetString("ERR_ENUM_GATEWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian phục vụ đơn hàng nằm ngoài lịch trình..
        /// </summary>
        public static string ERR_EVENT_ORDER_PERIOD {
            get {
                return ResourceManager.GetString("ERR_EVENT_ORDER_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng này đang bảo trì. Vui lòng thử lại sau..
        /// </summary>
        public static string ERR_FUNCTION_DOWN {
            get {
                return ResourceManager.GetString("ERR_FUNCTION_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần cung cấp từ {0} - {1} ảnh..
        /// </summary>
        public static string ERR_IMAGE_COUNT {
            get {
                return ResourceManager.GetString("ERR_IMAGE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có ảnh tới từ nguồn không hợp lệ..
        /// </summary>
        public static string ERR_IMAGE_SOURCE_INVALID {
            get {
                return ResourceManager.GetString("ERR_IMAGE_SOURCE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng đang phát triển..
        /// </summary>
        public static string ERR_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("ERR_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng chỉ có thể huỷ trong vòng {0} ngày kể từ khi đặt..
        /// </summary>
        public static string ERR_ORDER_CANCEL_DATE {
            get {
                return ResourceManager.GetString("ERR_ORDER_CANCEL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do huỷ đơn phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_ORDER_CANCEL_REASON_LENGTH {
            get {
                return ResourceManager.GetString("ERR_ORDER_CANCEL_REASON_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng không thể huỷ sau khi đã được phục vụ..
        /// </summary>
        public static string ERR_ORDER_CANCEL_STATUS {
            get {
                return ResourceManager.GetString("ERR_ORDER_CANCEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung đánh giá phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_ORDER_COMMENT_LENGTH {
            get {
                return ResourceManager.GetString("ERR_ORDER_COMMENT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn hàng..
        /// </summary>
        public static string ERR_ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú cho đơn hàng tối đa dài {0} ký tự..
        /// </summary>
        public static string ERR_ORDER_NOTE_LENGTH {
            get {
                return ResourceManager.GetString("ERR_ORDER_NOTE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phục vụ đơn gần nhất phải cách hôm nay ít nhất {0} ngày..
        /// </summary>
        public static string ERR_ORDER_OUT_OF_TIME {
            get {
                return ResourceManager.GetString("ERR_ORDER_OUT_OF_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thời gian tương ứng..
        /// </summary>
        public static string ERR_ORDER_PERIOD_INVALID {
            get {
                return ResourceManager.GetString("ERR_ORDER_PERIOD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã bị huỷ, không thể đặt hàng/dịch vụ..
        /// </summary>
        public static string ERR_ORDER_PLAN_CANCEL {
            get {
                return ResourceManager.GetString("ERR_ORDER_PLAN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã kết thúc, không thể đặt hàng/dịch vụ..
        /// </summary>
        public static string ERR_ORDER_PLAN_POST_READY {
            get {
                return ResourceManager.GetString("ERR_ORDER_PLAN_POST_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chốt danh sách thành viên kế hoạch, không thể đặt hàng/dịch vụ..
        /// </summary>
        public static string ERR_ORDER_PLAN_PRE_READY {
            get {
                return ResourceManager.GetString("ERR_ORDER_PLAN_PRE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đặt hàng sau khi kế hoạch đã bắt đầu..
        /// </summary>
        public static string ERR_ORDER_PLAN_STARTED {
            get {
                return ResourceManager.GetString("ERR_ORDER_PLAN_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng phải có từ {0} - {1} loại sản phẩm/dịch vụ khác nhau..
        /// </summary>
        public static string ERR_ORDER_PRODUCT_COUNT {
            get {
                return ResourceManager.GetString("ERR_ORDER_PRODUCT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sản phẩm không khả dụng..
        /// </summary>
        public static string ERR_ORDER_PRODUCT_INACTIVE {
            get {
                return ResourceManager.GetString("ERR_ORDER_PRODUCT_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sản phẩm/dịch vụ không được phục vụ vào thời gian này trong ngày..
        /// </summary>
        public static string ERR_ORDER_PRODUCT_PERIOD {
            get {
                return ResourceManager.GetString("ERR_ORDER_PRODUCT_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sản phẩm/dịch vụ không thuộc dịch vụ lưu trú..
        /// </summary>
        public static string ERR_ORDER_PRODUCT_TYPE_LODGING {
            get {
                return ResourceManager.GetString("ERR_ORDER_PRODUCT_TYPE_LODGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sản phẩm/dịch vụ không thuộc dịch vụ ăn uống..
        /// </summary>
        public static string ERR_ORDER_PRODUCT_TYPE_MEAL {
            get {
                return ResourceManager.GetString("ERR_ORDER_PRODUCT_TYPE_MEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sản phẩm/dịch vụ không thuộc dịch vụ thuê xe..
        /// </summary>
        public static string ERR_ORDER_PRODUCT_TYPE_RIDING {
            get {
                return ResourceManager.GetString("ERR_ORDER_PRODUCT_TYPE_RIDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm/dịch vụ không đến từ cùng 1 nhà cung cấp..
        /// </summary>
        public static string ERR_ORDER_PROVIDER_DIFF {
            get {
                return ResourceManager.GetString("ERR_ORDER_PROVIDER_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đã bị huỷ, không thể đánh giá..
        /// </summary>
        public static string ERR_ORDER_RATING_CANCELED {
            get {
                return ResourceManager.GetString("ERR_ORDER_RATING_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã quá hạn đánh giá đơn hàng..
        /// </summary>
        public static string ERR_ORDER_RATING_FINISHED {
            get {
                return ResourceManager.GetString("ERR_ORDER_RATING_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đánh giá dơn hàng chưa được phục vụ..
        /// </summary>
        public static string ERR_ORDER_RATING_NOT_SERVED {
            get {
                return ResourceManager.GetString("ERR_ORDER_RATING_NOT_SERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đánh giá đơn hàng rồi..
        /// </summary>
        public static string ERR_ORDER_RATING_RATED {
            get {
                return ResourceManager.GetString("ERR_ORDER_RATING_RATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá đơn hàng phải từ {0} - {1} sao..
        /// </summary>
        public static string ERR_ORDER_RATING_VALUE {
            get {
                return ResourceManager.GetString("ERR_ORDER_RATING_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phục vụ đơn hàng phải nằm trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_ORDER_SERVE_DATE {
            get {
                return ResourceManager.GetString("ERR_ORDER_SERVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau {0}, đơn hàng mới có thể đánh dấu đã phục vụ..
        /// </summary>
        public static string ERR_ORDER_SERVE_INVALID {
            get {
                return ResourceManager.GetString("ERR_ORDER_SERVE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đơn hàng không hợp lệ..
        /// </summary>
        public static string ERR_ORDER_STATUS_INVALID {
            get {
                return ResourceManager.GetString("ERR_ORDER_STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đơn hàng không thích hợp..
        /// </summary>
        public static string ERR_ORDER_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ERR_ORDER_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP cũ chưa hết hạn sử dụng. Không thể tạo OTP mới..
        /// </summary>
        public static string ERR_OTP_EXPIRY {
            get {
                return ResourceManager.GetString("ERR_OTP_EXPIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP không hợp lệ..
        /// </summary>
        public static string ERR_OTP_INVALID {
            get {
                return ResourceManager.GetString("ERR_OTP_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP phải gồm {0} ký tự..
        /// </summary>
        public static string ERR_OTP_LENGTH {
            get {
                return ResourceManager.GetString("ERR_OTP_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được để trống..
        /// </summary>
        public static string ERR_PHONE_EMPTY {
            get {
                return ResourceManager.GetString("ERR_PHONE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng số điện thoại không phù hợp..
        /// </summary>
        public static string ERR_PHONE_FORMAT {
            get {
                return ResourceManager.GetString("ERR_PHONE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bị trưởng đoàn cấm tham gia kế hoạch..
        /// </summary>
        public static string ERR_PLAN_BLOCKED {
            get {
                return ResourceManager.GetString("ERR_PLAN_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch này đã bị huỷ trước đó..
        /// </summary>
        public static string ERR_PLAN_CANCEL_CANCELED {
            get {
                return ResourceManager.GetString("ERR_PLAN_CANCEL_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tham gia kế hoạch đã bị huỷ..
        /// </summary>
        public static string ERR_PLAN_CANCEL_CANNOT_JOIN {
            get {
                return ResourceManager.GetString("ERR_PLAN_CANCEL_CANNOT_JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể huỷ kế hoạch đã chốt..
        /// </summary>
        public static string ERR_PLAN_CANCEL_READY {
            get {
                return ResourceManager.GetString("ERR_PLAN_CANCEL_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thành viên nhóm phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PLAN_COMPANION_NAME_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PLAN_COMPANION_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã bị huỷ bỏ, không thể chốt danh sách thành vièn..
        /// </summary>
        public static string ERR_PLAN_CONFIRM_CANCELED {
            get {
                return ResourceManager.GetString("ERR_PLAN_CONFIRM_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã chốt danh sách thành viên trước đó..
        /// </summary>
        public static string ERR_PLAN_CONFIRM_CONFIRMED {
            get {
                return ResourceManager.GetString("ERR_PLAN_CONFIRM_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch chưa vào trạng thái đăng ký, không thể chốt danh sách thành viên..
        /// </summary>
        public static string ERR_PLAN_CONFIRM_PENDING {
            get {
                return ResourceManager.GetString("ERR_PLAN_CONFIRM_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch phải lưu từ {0} - {1} thông tin liên lạc..
        /// </summary>
        public static string ERR_PLAN_CONTACT_COUNT {
            get {
                return ResourceManager.GetString("ERR_PLAN_CONTACT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn liên lạc khẩn cấp..
        /// </summary>
        public static string ERR_PLAN_CONTACT_EMERGENCY {
            get {
                return ResourceManager.GetString("ERR_PLAN_CONTACT_EMERGENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm xuất phát phải cách thời điểm hiện tại {0} - {1} ngày..
        /// </summary>
        public static string ERR_PLAN_DEPART_DATE {
            get {
                return ResourceManager.GetString("ERR_PLAN_DEPART_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm cứu hộ ở quá xa ( &gt; {0}m).
        /// </summary>
        public static string ERR_PLAN_EMERGENCY_DISTANCE {
            get {
                return ResourceManager.GetString("ERR_PLAN_EMERGENCY_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả chi tiết của hoạt động phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PLAN_EVENT_DESC_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PLAN_EVENT_DESC_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời lượng của hoạt động phải từ {0} - {1}..
        /// </summary>
        public static string ERR_PLAN_EVENT_DURATION {
            get {
                return ResourceManager.GetString("ERR_PLAN_EVENT_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả khái quát của hoạt động phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PLAN_EVENT_SHORT_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PLAN_EVENT_SHORT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng hoạt động không hợp lệ..
        /// </summary>
        public static string ERR_PLAN_EVENT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ERR_PLAN_EVENT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch với sĩ số dưới {0} chỉ có thể tạo nhóm cố định tối đa {1} người..
        /// </summary>
        public static string ERR_PLAN_FIXED_MEMBER_WEIGHT {
            get {
                return ResourceManager.GetString("ERR_PLAN_FIXED_MEMBER_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã mời {0} tham gia trước đó..
        /// </summary>
        public static string ERR_PLAN_INVITE_INVITED {
            get {
                return ResourceManager.GetString("ERR_PLAN_INVITE_INVITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tham gia kế hoạch rồi..
        /// </summary>
        public static string ERR_PLAN_INVITE_JOINED {
            get {
                return ResourceManager.GetString("ERR_PLAN_INVITE_JOINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức tham gia kế hoạch hiện tại không cho phép mời người dùng khác tham gia kế hoạch..
        /// </summary>
        public static string ERR_PLAN_INVITE_METHOD {
            get {
                return ResourceManager.GetString("ERR_PLAN_INVITE_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không muốn nhận lời mời tham gia kế hoạch này thêm nữa..
        /// </summary>
        public static string ERR_PLAN_INVITE_SELF_BLOCKED {
            get {
                return ResourceManager.GetString("ERR_PLAN_INVITE_SELF_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch không ở trạng thái chờ đăng ký, không thể mời người khác tham gia..
        /// </summary>
        public static string ERR_PLAN_INVITE_STATUS_REGISTERING {
            get {
                return ResourceManager.GetString("ERR_PLAN_INVITE_STATUS_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã đủ thành viên..
        /// </summary>
        public static string ERR_PLAN_JOIN_FULL {
            get {
                return ResourceManager.GetString("ERR_PLAN_JOIN_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch chỉ còn {0} slot tham gia..
        /// </summary>
        public static string ERR_PLAN_JOIN_MAX {
            get {
                return ResourceManager.GetString("ERR_PLAN_JOIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức tham gia không hợp lệ..
        /// </summary>
        public static string ERR_PLAN_JOIN_METHOD_INVALID {
            get {
                return ResourceManager.GetString("ERR_PLAN_JOIN_METHOD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức tham gia mới phải khác phương thức tham gia cũ..
        /// </summary>
        public static string ERR_PLAN_JOIN_METHOD_UNCHANGE {
            get {
                return ResourceManager.GetString("ERR_PLAN_JOIN_METHOD_UNCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng đoàn chỉ cho phép nhóm tham gia có tối đa {0} người..
        /// </summary>
        public static string ERR_PLAN_JOIN_WEIGHT {
            get {
                return ResourceManager.GetString("ERR_PLAN_JOIN_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tham gia kế hoạch này trước đó..
        /// </summary>
        public static string ERR_PLAN_JOINED {
            get {
                return ResourceManager.GetString("ERR_PLAN_JOINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thành viên tối đa của 1 nhóm phải ít hơn {0} người..
        /// </summary>
        public static string ERR_PLAN_MEMBER_MAX_WEIGHT {
            get {
                return ResourceManager.GetString("ERR_PLAN_MEMBER_MAX_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thành viên tối đa của 1 nhóm phải nhiều hơn {0} người..
        /// </summary>
        public static string ERR_PLAN_MEMBER_MIN_WEIGHT {
            get {
                return ResourceManager.GetString("ERR_PLAN_MEMBER_MIN_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin về thành viên..
        /// </summary>
        public static string ERR_PLAN_MEMBER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_PLAN_MEMBER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thành viên của kế hoạch đoàn thể phải từ {0} - {1} người..
        /// </summary>
        public static string ERR_PLAN_MEMBER_RANGE {
            get {
                return ResourceManager.GetString("ERR_PLAN_MEMBER_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kế hoạch phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PLAN_NAME_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PLAN_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin về kế hoạch..
        /// </summary>
        public static string ERR_PLAN_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_PLAN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được mời tham gia kế hoạch..
        /// </summary>
        public static string ERR_PLAN_NOT_INVITED {
            get {
                return ResourceManager.GetString("ERR_PLAN_NOT_INVITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú kế hoạch dài tối đa {0} ký tự..
        /// </summary>
        public static string ERR_PLAN_NOTE_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PLAN_NOTE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian trải nghiệm phải nằm trong khoảng từ {0} - {1} ngày. .
        /// </summary>
        public static string ERR_PLAN_PERIOD {
            get {
                return ResourceManager.GetString("ERR_PLAN_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch cá nhân chỉ có thể có 1 thành viên tham gia..
        /// </summary>
        public static string ERR_PLAN_PERSONAL_JOIN {
            get {
                return ResourceManager.GetString("ERR_PLAN_PERSONAL_JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo nhóm trong kế hoạch cá nhân..
        /// </summary>
        public static string ERR_PLAN_PERSONAL_MEMBER_WEIGHT {
            get {
                return ResourceManager.GetString("ERR_PLAN_PERSONAL_MEMBER_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tham gia kế hoạch riêng tư..
        /// </summary>
        public static string ERR_PLAN_PRIVATE {
            get {
                return ResourceManager.GetString("ERR_PLAN_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng cách giữa nhà cung cấp và địa điểm du lịch quá xa ( &gt; {0}m).
        /// </summary>
        public static string ERR_PLAN_PROVIDER_DISTANCE {
            get {
                return ResourceManager.GetString("ERR_PLAN_PROVIDER_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch chưa được xác nhận bởi hệ thống, không thể xuất bản..
        /// </summary>
        public static string ERR_PLAN_PUBLISH_STATUS {
            get {
                return ResourceManager.GetString("ERR_PLAN_PUBLISH_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã chốt danh sách thành viên, không thể tham gia..
        /// </summary>
        public static string ERR_PLAN_READY_CANNOT_JOIN {
            get {
                return ResourceManager.GetString("ERR_PLAN_READY_CANNOT_JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ có thể thay đổi phương thức tham gia khi kế hoạch ở trạng thái chờ đăng ký..
        /// </summary>
        public static string ERR_PLAN_REGISTERING_JOIN_METHOD {
            get {
                return ResourceManager.GetString("ERR_PLAN_REGISTERING_JOIN_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng đoàn không thể rời kế hoạch..
        /// </summary>
        public static string ERR_PLAN_REMOVE_HOST {
            get {
                return ResourceManager.GetString("ERR_PLAN_REMOVE_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ có thể loại thành viên khi kế hoạch đang ở trạng thái chờ đăng ký..
        /// </summary>
        public static string ERR_PLAN_REMOVE_MEMBER_REGISTERING {
            get {
                return ResourceManager.GetString("ERR_PLAN_REMOVE_MEMBER_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời lượng lịch trình ngày đầu tiên đã vượt quá thời gian còn lại trong ngày..
        /// </summary>
        public static string ERR_PLAN_SCHEDULE_DURATION_FIRST {
            get {
                return ResourceManager.GetString("ERR_PLAN_SCHEDULE_DURATION_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời lượng lịch trình ngày cuối cùng đã vượt quá buổi trưa..
        /// </summary>
        public static string ERR_PLAN_SCHEDULE_DURATION_LAST {
            get {
                return ResourceManager.GetString("ERR_PLAN_SCHEDULE_DURATION_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời lượng lịch trình trong ngày không thể vượt quá {0}..
        /// </summary>
        public static string ERR_PLAN_SCHEDULE_DURATION_MID {
            get {
                return ResourceManager.GetString("ERR_PLAN_SCHEDULE_DURATION_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời lượng lịch trình không trùng khớp với thời gian trải nghiệm..
        /// </summary>
        public static string ERR_PLAN_SCHEDULE_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PLAN_SCHEDULE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ có thể rời khỏi kế hoạch khi kế hoạch đang ở trạng thái chờ đăng ký..
        /// </summary>
        public static string ERR_PLAN_SELF_REMOVE_REGISTERING {
            get {
                return ResourceManager.GetString("ERR_PLAN_SELF_REMOVE_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy kế hoạch mẫu..
        /// </summary>
        public static string ERR_PLAN_SOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_PLAN_SOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch chỉ có thể có tối đa {0} khoản phụ thu..
        /// </summary>
        public static string ERR_PLAN_SURCHARGE_MAX_COUNT {
            get {
                return ResourceManager.GetString("ERR_PLAN_SURCHARGE_MAX_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú phụ thu phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PLAN_SURCHARGE_NOTE_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PLAN_SURCHARGE_NOTE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoản phụ thu phải từ {0} - {1} Gcoin..
        /// </summary>
        public static string ERR_PLAN_SURCHARGE_RANGE {
            get {
                return ResourceManager.GetString("ERR_PLAN_SURCHARGE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật thông tin của kế hoạch đã bị huỷ..
        /// </summary>
        public static string ERR_PLAN_UPDATE_STATUS_CANCEL {
            get {
                return ResourceManager.GetString("ERR_PLAN_UPDATE_STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật thông tin kế hoạch sau khi đã tham gia..
        /// </summary>
        public static string ERR_PLAN_UPDATE_STATUS_POST_PENDING {
            get {
                return ResourceManager.GetString("ERR_PLAN_UPDATE_STATUS_POST_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã bị huỷ trước đó, không thể thực hiện..
        /// </summary>
        public static string ERR_PLAN_VERIFY_CANCELED {
            get {
                return ResourceManager.GetString("ERR_PLAN_VERIFY_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng check in cho kế hoạch này chưa được mở khoá, vui lòng chờ đến {0}..
        /// </summary>
        public static string ERR_PLAN_VERIFY_DEPART_TIME {
            get {
                return ResourceManager.GetString("ERR_PLAN_VERIFY_DEPART_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã kết thúc, không thể thực hiện..
        /// </summary>
        public static string ERR_PLAN_VERIFY_FLAWED {
            get {
                return ResourceManager.GetString("ERR_PLAN_VERIFY_FLAWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in thất bại. Vui lòng tới gần điểm du lịch hơn..
        /// </summary>
        public static string ERR_PLAN_VERIFY_OUT_RANGE {
            get {
                return ResourceManager.GetString("ERR_PLAN_VERIFY_OUT_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch chưa được chốt, không thể thực hiện..
        /// </summary>
        public static string ERR_PLAN_VERIFY_PRE_READY {
            get {
                return ResourceManager.GetString("ERR_PLAN_VERIFY_PRE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã được xác nhận trước đó..
        /// </summary>
        public static string ERR_PLAN_VERIFY_VERIFIED {
            get {
                return ResourceManager.GetString("ERR_PLAN_VERIFY_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả sản phẩm dịch vụ phải nằm trong khoảng từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PRODUCT_DESCRIPTION_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_DESCRIPTION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm/dịch vụ phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PRODUCT_NAME_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm..
        /// </summary>
        public static string ERR_PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số người phù hợp với sản phảm/dịch vụ phải nằm trong khoảng từ {0} - {1} người..
        /// </summary>
        public static string ERR_PRODUCT_PARTYSIZE_RANGE {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_PARTYSIZE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thời gian tương ứng..
        /// </summary>
        public static string ERR_PRODUCT_PERIOD_INVALID {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_PERIOD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá sản phẩm/dịch vụ phải nằm trong khoảng {0} - {1}đ..
        /// </summary>
        public static string ERR_PRODUCT_PRICE_RANGE {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_PRICE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm/dịch vụ không thích hợp..
        /// </summary>
        public static string ERR_PRODUCT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá mới của sản phẩm/dịch vụ không thể cao hơn {0}% so với giá cũ..
        /// </summary>
        public static string ERR_PRODUCT_UPDATE_PRICE_UP {
            get {
                return ResourceManager.GetString("ERR_PRODUCT_UPDATE_PRICE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp này đã được cấp tài khoản trước đó..
        /// </summary>
        public static string ERR_PROVIDER_ACCOUNT_EXISTED {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_ACCOUNT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp không còn hoạt động trên hệ thống..
        /// </summary>
        public static string ERR_PROVIDER_INACTIVE {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp phải từ {0} - {1} ký tự..
        /// </summary>
        public static string ERR_PROVIDER_NAME_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn nhà hàng/khách sạn phải từ {0}* - {1}*.
        /// </summary>
        public static string ERR_PROVIDER_NEED_STANDARD {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_NEED_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình nhà cung cấp này không có đánh giá tiêu chuẩn..
        /// </summary>
        public static string ERR_PROVIDER_NO_STANDARD {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_NO_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hỗ trợ truy cập hệ thống đối với mô hình nhà cung cấp này..
        /// </summary>
        public static string ERR_PROVIDER_NO_SUPPORT_ACCESS {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_NO_SUPPORT_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hỗ trợ kinh doanh sản phẩm/dịch vụ đối với mô hình nhà cung cấp này..
        /// </summary>
        public static string ERR_PROVIDER_NO_SUPPORT_PRODUCT {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_NO_SUPPORT_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin nhà cung cấp..
        /// </summary>
        public static string ERR_PROVIDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin của 1 số nhà cung cấp..
        /// </summary>
        public static string ERR_PROVIDER_NOT_FOUND_SOME {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_NOT_FOUND_SOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô hình dịch vụ không hợp lệ..
        /// </summary>
        public static string ERR_PROVIDER_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình dịch vụ hiện tại của nhà cung cấp không cùng nhóm với loại hình mới..
        /// </summary>
        public static string ERR_PROVIDER_TYPE_UPDATE_CONFLICT {
            get {
                return ResourceManager.GetString("ERR_PROVIDER_TYPE_UPDATE_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tỉnh thành..
        /// </summary>
        public static string ERR_PROVINCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_PROVINCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoản phụ thu đã được cập nhật hoá đơn trước đó..
        /// </summary>
        public static string ERR_SURCHARGE_ALREADY_UPDATED {
            get {
                return ResourceManager.GetString("ERR_SURCHARGE_ALREADY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy khoản phụ thu.
        /// </summary>
        public static string ERR_SURCHARGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SURCHARGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã huỷ, không thể cập nhật hoá đơn..
        /// </summary>
        public static string ERR_SURCHARGE_PLAN_CANCEL {
            get {
                return ResourceManager.GetString("ERR_SURCHARGE_PLAN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch đã kết thúc, không thể cập nhật hoá đơn..
        /// </summary>
        public static string ERR_SURCHARGE_PLAN_POST_READY {
            get {
                return ResourceManager.GetString("ERR_SURCHARGE_PLAN_POST_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch chưa chốt, không thể cập nhật hoá đơn..
        /// </summary>
        public static string ERR_SURCHARGE_PLAN_PRE_READY {
            get {
                return ResourceManager.GetString("ERR_SURCHARGE_PLAN_PRE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh không hợp lệ/đã hết hạn sử dụng..
        /// </summary>
        public static string ERR_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("ERR_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền nạp phải nằm trong khoảng {0} - {1}..
        /// </summary>
        public static string ERR_TOPUP_AMOUNT {
            get {
                return ResourceManager.GetString("ERR_TOPUP_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin giao dịch..
        /// </summary>
        public static string ERR_TRANSACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_TRANSACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin người nhận..
        /// </summary>
        public static string ERR_TRANSACTION_RECEIVER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_TRANSACTION_RECEIVER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền nạp không đồng bộ..
        /// </summary>
        public static string ERR_TRANSACTION_VNPAY_AMOUNT {
            get {
                return ResourceManager.GetString("ERR_TRANSACTION_VNPAY_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận được kết quả giao dịch..
        /// </summary>
        public static string ERR_TRANSACTION_VNPAY_EMPTY {
            get {
                return ResourceManager.GetString("ERR_TRANSACTION_VNPAY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chữ ký không hợp lệ..
        /// </summary>
        public static string ERR_TRANSACTION_VNPAY_SIGNATURE {
            get {
                return ResourceManager.GetString("ERR_TRANSACTION_VNPAY_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái giao dịch không hợp lệ..
        /// </summary>
        public static string ERR_TRANSACTION_VNPAY_STATUS {
            get {
                return ResourceManager.GetString("ERR_TRANSACTION_VNPAY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không rõ..
        /// </summary>
        public static string ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thành công..
        /// </summary>
        public static string SUC_TRANSACTION_VNPAY {
            get {
                return ResourceManager.GetString("SUC_TRANSACTION_VNPAY", resourceCulture);
            }
        }
    }
}
