name: Build and deploy BTSS API to an Azure Web App

env:
  AZURE_WEBAPP_NAME: btssappv2
  AZURE_WEBAPP_PACKAGE_PATH: './published-app'
  AZURE_WEBAPP_PUBLISH_PATH: './publish'
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # - name: Build with dotnet
      #   run: dotnet build --configuration Release

      - name: build with dotnet and publish
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PUBLISH_PATH }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PUBLISH_PATH }}

      #- name: Upload artifact for deployment job
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: .net-app
      #    path: ${{ env.AZURE_WEBAPP_PUBLISH_PATH }}/**
      #    if-no-files-found: error
      #    retention-days: 2

  #deploy:
  #  permissions:
  #    contents: none
  #  runs-on: windows-latest
  #  needs: build
  #  environment:
  #    name: 'Development'
  #    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #  steps:
      #- name: Download artifact from build job
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: .net-app
      #    path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  #    - name: Deploy to Azure Web App
  #      id: deploy-to-webapp
  #      uses: azure/webapps-deploy@v2
  #      with:
  #        app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #        package: ${{ env.AZURE_WEBAPP_PUBLISH_PATH }}